### ISSUE TITLE
Navi10 support on launch day? 

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Tools/Radeon-GPUProfiler#28]
Hi,
just asking if we can expect an new RGP release on Navi launch day (7 july) or shortly after with support for 5700XT..
if not some ETA?
thanks..

**Comment by tbotting** [comment]
I'm also waiting for Navi support

**Comment by ahosier** [comment]
RGP with Navi support will be available in the next couple of weeks once full tool support has been added to the driver.

Thankyou for your comment and your interest in RGP
Tony.

**Comment by tbotting** [comment]
Thanks for the fast response, I think for AMD it would be better if these tools were made available/updated right at launch. That way application developers can optimize their programs as fast as possible. Closing (or increasing?) the gap further to Nvidia 😉

**Comment by tbotting** [comment]
Hello, the  'Radeon Software Adrenalin 2019 Edition 19.7.3 Highlights' state that 'Radeon GPU Profiler on Radeon RX 5700 series graphics products' is now supported. Does that mean that I should be able to use the profiler now? Or does this mean the developers of the profiler are now able to use the support that the drivers offer?

**Comment by ahosier** [comment]
Hi,

RGP v1.5.1 will allow you to take captures on Navi since that support is in the driver, but the RGP viewer for 1.5.1 doesn't have Navi support to view those traces. We were hoping RGP V1.6 released today but a couple last minute issues arose that we're looking into. Should be any day now but I'll keep you posted.

Thanks for your interest in RGP,
Tony.

**Comment by ahosier** [comment]
Hi,

RGP V1.6 is now live! Thank you for your patience.

Tony.

**Comment by oscarbg** [comment]
thanks!
