### ISSUE TITLE
ISA not displaying in 1.6 UI

### ISSUE THREAD

**Issue by robbiesri** [GPUOpen-Tools/Radeon-GPUProfiler#29]
I was just poking around the new 1.6 client, and realized that I wasn't able to see the ISA that was captured as part of the RGP trace. If I open the same trace inside the 1.5 client, I can see the ISA just fine.

I can't share the traces here, but happy to share some artifacts offline.

**Comment by bpurnomo** [comment]
Rob provided the RGP files offline.  After our investigation, the profiles were captured using a driver older than Adrenalin 19.5.1 (the minimum driver requirement to support the RGP isa disassembly feature).  RGP 1.5 can incorrectly show the isa disassembly on older drivers.  Since there is no action item to fix the latest version of RGP, I am closing this ticket.
